/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_heredata_ncdfs_NCDFSJ */

#ifndef _Included_com_heredata_ncdfs_NCDFSJ
#define _Included_com_heredata_ncdfs_NCDFSJ
#ifdef __cplusplus
extern "C" {
#endif
#undef com_heredata_ncdfs_NCDFSJ_dirType_w
#define com_heredata_ncdfs_NCDFSJ_dirType_w 3L
#undef com_heredata_ncdfs_NCDFSJ_dirType_10w
#define com_heredata_ncdfs_NCDFSJ_dirType_10w 2L
#undef com_heredata_ncdfs_NCDFSJ_dirType_100w
#define com_heredata_ncdfs_NCDFSJ_dirType_100w 0L
/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_login
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1login
  (JNIEnv *, jobject, jstring, jstring, jstring, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_stat
 * Signature: (Ljava/lang/String;Lcom/heredata/ncdfs/model/JStat;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1stat
  (JNIEnv *, jobject, jstring, jobject, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_access
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1access
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_mkdir
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1mkdir
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    open_dir
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_heredata_ncdfs_NCDFSJ_open_1dir
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    read_dir
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_heredata_ncdfs_NCDFSJ_read_1dir
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    close_dir
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_heredata_ncdfs_NCDFSJ_close_1dir
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    rewind_dir
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_heredata_ncdfs_NCDFSJ_rewind_1dir
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_rename
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1rename
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_remove
 * Signature: (Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1remove
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_open
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1open
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_write
 * Signature: (Ljava/lang/String;JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1write__Ljava_lang_String_2JJJ
  (JNIEnv *, jobject, jstring, jlong, jlong, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_write
 * Signature: ([BJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1write___3BJJJ
  (JNIEnv *, jobject, jbyteArray, jlong, jlong, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_read
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1read__JJJ
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_read
 * Signature: ([BJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1read___3BJJJ
  (JNIEnv *, jobject, jbyteArray, jlong, jlong, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_flush
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1flush
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_eof
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1eof
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_seek
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1seek
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_tell
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1tell
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_rewind
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1rewind
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_link
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1link
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_unlink
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1unlink
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_chown
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1chown
  (JNIEnv *, jobject, jstring, jstring, jstring, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_chmod
 * Signature: (Ljava/lang/String;JJ)I
 */
JNIEXPORT jint JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1chmod
  (JNIEnv *, jobject, jstring, jlong, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_destory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1destory
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_ver
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1ver
  (JNIEnv *, jobject);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    adapter_setdir
 * Signature: (Ljava/lang/String;IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_heredata_ncdfs_NCDFSJ_adapter_1setdir
  (JNIEnv *, jobject, jstring, jint, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    SS_ISREG
 * Signature: (Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_heredata_ncdfs_NCDFSJ_SS_1ISREG
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    SS_ISDIR
 * Signature: (Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_heredata_ncdfs_NCDFSJ_SS_1ISDIR
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    getlen
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_heredata_ncdfs_NCDFSJ_getlen
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    getlastModified
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_heredata_ncdfs_NCDFSJ_getlastModified
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_heredata_ncdfs_NCDFSJ
 * Method:    getlist
 * Signature: (Ljava/lang/String;J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_heredata_ncdfs_NCDFSJ_getlist
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
